# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs"
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: cole.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer

# ---------------------------------------------------------------------------
# "PeerOrgs"
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Companya
  # ---------------------------------------------------------------------------
  - Name: Companya
    Domain: companya.cole.com
    # Companya有两个节点，分别是 # peer0.companya.cole.com，peer1.companya.cole.com
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Companyb
  # ---------------------------------------------------------------------------
  - Name: Companyb
    Domain: companyb.cole.com
    # Companyb有两个节点，分别是 # peer0.companyb.cole.com，peer1.companyb.cole.com
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Accountservice
    Domain: accountservice.cole.com
    # Companyc有两个节点，分别是 # peer0.accountservice.cole.com，peer1.accountservice.cole.com
    Template:
      Count: 2
    Users:
      Count: 1
